nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://127.0.0.1:5501']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:5501']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            
            

