controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [GET, POST]

api_signup:
    path: /api/signup
    controller: App\Controller\UserController::signup
    methods: POST

api_login:
    path: /api/login
    controller: App\Controller\UserController::login
    methods: POST
