controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_signup:
    path: /api/signup
    controller: App\Controller\UserController::signup
    methods: [POST]

api_login_check:
    path: /api/login_check
